function ASET_ExportXlsFile(vars)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function creates the EXCEL Files and export the file.
%
% by Dominguez Ruben, L. FICH-UNL
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Read data
 guiparams = getappdata(0,'guiparams');%Calculated data
 ADCP=getappdata(0,'ADCPdata');%Parameters data   
    
for t=1:size(guiparams,2)%check number of files
    
    %Read data of calculate
    if iscell(guiparams)%multi select
        V   = guiparams{t}.V;
        S   = guiparams{t}.S;
        Css   = guiparams{t}.Css;
        Meas   = guiparams{t}.Meas;
        NoMeas   = guiparams{t}.NoMeas;
        Array = guiparams{t}.Array;
        QEdge = guiparams{t}.QEdge;
        Dis = guiparams{t}.Dis;
        VelExtraM = guiparams{t}.VelExtraM;
        CssExtraM = guiparams{t}.CssExtraM;
        FileName = guiparams{t}.FileName;
        FileNamePD0 = guiparams{t}.FileNamePD0;        
    else
        V = guiparams.V;
        S   = guiparams.S;
        Css = guiparams.Css;
        Meas = guiparams.Meas;
        NoMeas   = guiparams.NoMeas;
        Array = guiparams.Array;
        QEdge = guiparams.QEdge;
        Dis = guiparams.Dis;
        VelExtraM = guiparams.VelExtraM;
        CssExtraM = guiparams.CssExtraM;
        FileName = guiparams.FileName;
        FileNamePD0 = guiparams.FileNamePD0; 
    end
    

    message=['Save Excel file of ' FileName];
    [file,path] = uiputfile('*.xlsx',message);

    
    if file==0
        break
    else
        outfile = fullfile(path,file);
        waitmessage=['Exporting Excel File...' file];
        hwait = waitbar(0,waitmessage,'Name','ASET');
    
         if vars.units==0 %metric system
            %Create the first sheet
            data1 = {...
                'ASET: Summary of Data Analysis' '' '' '' '' '';...
                'Date Processed: ' datestr(now) '' '' '' '';...
                '' '' '' '' '' '';...
                'Cross Section Data' '' '' '' '' '';...
                'Name File:' '' '' '' '' FileName ;...
                'PD0 Name File:' '' '' '' '' FileNamePD0;...
                'Distance cross section [m]:' '' '' '' '' round(V.mcsDist(1,end),2);...
                'Average Depth [m]:' '' '' '' '' round(nanmean(Array.Bed),2);...   
                '' '' '' '' '' '';...
                'ASET: Hydraulics Variables' '' '' '' '' '';...
                'Average Velocity [cm/s]:' '' '' '' '' round(nanmean(nanmean(Array.uMag)),2);...
                'Velocity Extrapolation Method:' '' '' '' '' VelExtraM;...
                'Total Liquid Discharge [m3/s]:' '' '' '' '' round(Dis.Total+QEdge.Q.left+QEdge.Q.right,2);...   
                'Surface Liquid Discharge [m3/s]:' '' '' '' '' round(Dis.surfT,2);...   
                'Measured Liquid Discharge [m3/s]:' '' '' '' '' round(Dis.Meas,2);...   
                'Bottom Liquid Discharge [m3/s]:' '' '' '' '' round(Dis.bottomT,2);...   
                'Left Liquid Discharge [m3/s]:' '' '' '' '' round(QEdge.Q.left,2);...   
                'Right Liquid Discharge [m3/s]:' '' '' '' '' round(QEdge.Q.right,2);...
                '' '' '' '' '' '';...
                'ASET: Sedimentology Variables' '' '' '' '' '';...
                'Ms1 Concentration [mg/l]:' '' '' '' '' round(S.Csf);...
                'Qw Total [kg/s]:' '' '' '' '' round(Array.GwT);...
                'Average Ms2 Concentration [mg/l]:' '' '' '' '' round(nanmean(nanmean(Array.Css))*1000,2);...
                'Ms2 Extrapolation Method:' '' '' '' '' CssExtraM;...
                'Qss Total [kg/s]:' '' '' '' '' round(Array.GssT,2);...
                'Surface Qss [kg/s]:' '' '' '' '' round(NoMeas.Surf.GssT,2);...   
                'Measured Qss [kg/s]:' '' '' '' '' round(Meas.GssT,2);...   
                'Bottom Qss [kg/s]:' '' '' '' ''  round(NoMeas.Bottom.GssT,2);...   
                'Left Qss [kg/s]:' '' '' '' '' round(QEdge.Gss.left,2);...   
                'Right Qss [kg/s]:' '' '' '' '' round(QEdge.Gss.right,2);...
                '' '' '' '' '' '';...
                'ADCP Configuration and Calibration Data' '' '' '' '' '';
                'ADCP model:' '' '' '' '' ADCP.typeADCP;...
                'ADCP Frequency [kHz]:' '' '' '' '' ADCP.Inst.freq;...
                'ADCP Cr coef:' '' '' '' '' ADCP.ccoef;...
                'ADCP RSSI Slope Beam 1:' '' '' '' '' ADCP.rssi_beam1;...
                'ADCP RSSI Slope Beam 2:' '' '' '' '' ADCP.rssi_beam2;...
                'ADCP RSSI Slope Beam 3:' '' '' '' '' ADCP.rssi_beam3;...
                'ADCP RSSI Slope Beam 4:' '' '' '' '' ADCP.rssi_beam4;...
                'Draft [m]:' '' '' '' '' round(ADCP.R.draft,2);...
                'kcEr Calibration' '' '' '' '' round(ADCP.kcEr,2);...
                '' '' '' '' '' ''};
        elseif vars.units==1 %English system
               %Create the first sheet
            data1 = {...
                'ASET: Summary of Data Analysis' '' '' '' '' '';...
                'Date Processed: ' datestr(now) '' '' '' '';...
                '' '' '' '' '' '';...
                'Cross Section Data' '' '' '' '' '';...
                'Name File:' '' '' '' '' FileName ;...
                'PD0 Name File:' '' '' '' '' FileNamePD0;...
                'Distance cross section [ft]:' '' '' '' '' round(V.mcsDist(1,end),2);...
                'Average Depth [ft]:' '' '' '' '' round(nanmean(Array.Bed),2);...   
                '' '' '' '' '' '';...
                'ASET: Hydraulics Variables' '' '' '' '' '';...
                'Average Velocity [ft/s]:' '' '' '' '' round(nanmean(nanmean(Array.uMag)),2);...
                'Velocity Extrapolation Method:' '' '' '' '' VelExtraM;...
                'Total Liquid Discharge [ft3/s]:' '' '' '' '' round(Dis.Total+QEdge.Q.left+QEdge.Q.right,2);...   
                'Surface Liquid Discharge [ft3/s]:' '' '' '' '' round(Dis.surfT,2);...   
                'Measured Liquid Discharge [ft3/s]:' '' '' '' '' round(Dis.Meas,2);...   
                'Bottom Liquid Discharge [ft3/s]:' '' '' '' '' round(Dis.bottomT,2);...   
                'Left Liquid Discharge [ft3/s]:' '' '' '' '' round(QEdge.Q.left,2);...   
                'Right Liquid Discharge [ft3/s]:' '' '' '' '' round(QEdge.Q.right,2);...
                '' '' '' '' '' '';...
                'ASET: Sedimentology Variables' '' '' '' '' '';...
                'Ms1 Concentration [t/l]:' '' '' '' '' round(S.Csf);...
                'Qw Total [t/s]:' '' '' '' '' round(Array.GwT);...
                'Average Ms2 Concentration [t/l]:' '' '' '' '' round(nanmean(nanmean(Css))*1000,2);...
                'Ms2 Extrapolation Method:' '' '' '' '' CssExtraM;...
                'Gss Total [t/s]:' '' '' '' '' round(Array.GssT,2);...
                'Surface Qss [t/s]:' '' '' '' '' round(NoMeas.Surf.GssT,2);...   
                'Measured Qss [t/s]:' '' '' '' '' round(Meas.GssT,2);...   
                'Bottom Qss [t/s]:' '' '' '' ''  round(NoMeas.Bottom.GssT,2);...   
                'Left Qss [t/s]:' '' '' '' '' round(QEdge.Gss.left,2);...   
                'Right Qss [t/s]:' '' '' '' '' round(QEdge.Gss.right,2);...
                '' '' '' '' '' '';...
                'ADCP Configuration and Calibration Data' '' '' '' '' '';
                'ADCP model:' '' '' '' '' ADCP.typeADCP;...
                'ADCP Frequency [kHz]:' '' '' '' '' ADCP.Inst.freq;...
                'ADCP C coef:' '' '' '' '' ADCP.ccoef;...
                'ADCP RSSI Slope Beam 1:' '' '' '' '' ADCP.rssi_beam1;...
                'ADCP RSSI Slope Beam 2:' '' '' '' '' ADCP.rssi_beam2;...
                'ADCP RSSI Slope Beam 3:' '' '' '' '' ADCP.rssi_beam3;...
                'ADCP RSSI Slope Beam 4:' '' '' '' '' ADCP.rssi_beam4;...
                'Draft [ft]:' '' '' '' '' round(ADCP.R.draft,2);...
                'kcEr Calibration' '' '' '' '' round(ADCP.kcEr,2);...
                '' '' '' '' '' ''};
        end


        xlswrite(outfile,data1,'ASET Summary','A1');
        waitbar(1/5,hwait)

        for j=1:size(Array.Depth_uMag,2)
           Distmody(1:size(Array.Depth_uMag,1),j) = Array.Dist(1,j);
           Bedmody(1:size(Array.Depth_uMag,1),j) = Array.Bed(1,j);
        end

       %Create the second sheet 
       headers2 = {...
            'Depth of Velocity Magnitude in m'...
            'Velocity Magnitude in cm/s'...
            'Depth of Concentration in m'...
            'Concentration Ms2 in kg/m3'...
            'Depth of Qss in m'...
            'Qss in Kg/s'...
            'Distance in m'...
            'Bed Elevation in m'...
            };

        data2 = [...
            Array.Depth_uMag(:)...
            Array.uMag(:)...
            Array.Depth_Css(:)...
            Array.Css(:)...
            Array.Depth_Gss(:)...
            Array.Gss(:)...
            Distmody(:)...       
            Bedmody(:)...
            ];

        waitbar(0.4,hwait)

        data2(isnan(data2)) = -9999;
        data2(data2==0)=-9999;

        waitbar(0.75,hwait)
        pvout2 = vertcat(headers2,num2cell(data2));
        xlswrite(outfile,pvout2, 'ASET Results');
        waitbar(1,hwait)
        delete(hwait)                       

        clear Css V Array Meas QEdge Dis VelExtraM CssExtraM S NoMeas Distmody Bedmody
        
        % Push messages to Log Window:
        % ----------------------------
        log_text = {...
            '';...
            ['%--- ' datestr(now) ' ---%'];...
            'Complete Export Excel File'; outfile};
            statusLogging(vars.LogWindow, log_text)
    
    end
end


